version: '3.7'

services:
  pg:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "ifmo-ws"
      POSTGRES_PASSWORD: "ifmo-ws"
    restart: on-failure
